---
services:
  homepage:
    image: rantanevich/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      HOMEPAGE_PORT: 3000
      HOMEPAGE_TITLE: HomePage
      HOMEPAGE_LOGO: homer.webp
      HOMEPAGE_PROVIDERS_FILE_FILENAME: /etc/homepage/config.yml
    volumes:
    - ./config:/etc/homepage:ro
    ports:
    - 3000:3000/tcp
