---
title: Example
logo: mike
icons: /etc/homepage/icons

categories:
- name: Entertainment
  services:
  - name: Instagram
    url: https://www.instagram.com/
    icon: instagram
  - name: Spotify
    url: https://open.spotify.com/
    icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/spotify.png
- name: Monitoring
  services:
  - name: Grafana
    description: Data visualization service
    url: https://grafana.example.com/
    icon: grafana.png
  - name: Prometheus
    description: Monitoring system
    url: https://prometheus.example.com/
    icon: prometheus
