---
Entertainment:
  Instagram:
    url: https://www.instagram.com/
    icon: sh-instagram
  Spotify:
    url: https://open.spotify.com/
    icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/spotify.png

Monitoring:
  Grafana:
    description: Data visualization service
    url: https://grafana.example.com/
    icon: grafana.png
  Prometheus:
    description: Monitoring system
    url: https://prometheus.example.com/
    icon: prometheus.webp
