---
title: Homepage
logo: logo.png
icons: /icons

categories:
- name: Management
  services:
  - name: Kafka UI
    url: https://grafana.worst.dynu.net/
    icon: kafka-ui.png
- name: Monitoring
  services:
  - name: Grafana
    description: Data visualization service
    url: https://grafana.worst.dynu.net/
    icon: grafana.png
  - name: Prometheus
    description: Monitoring system
    url: https://prometheus.worst.dynu.net/
    icon: prometheus
