---
name: Release

on:
  push:
    branches:
    - main
    tags:
    - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: rantanevich
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push to Docker Hub
      run: |
        GIT_BRANCH_NAME=${{ github.event.repository.default_branch }}
        GIT_SHORT_SHA=$(git rev-parse --short=10 HEAD)
        IMAGE_TAG=$GIT_BRANCH_NAME-$GIT_SHORT_SHA

        if [ '${{ github.ref_type }}' = 'tag' ]; then
          IMAGE_TAG=${{ github.ref_name }}
        fi

        docker buildx build \
            --push \
            --platform linux/amd64 \
            --tag rantanevich/homepage:$IMAGE_TAG \
            .
